fx_version 'adamant'
game 'gta5'

data_file 'DLC_ITYP_REQUEST' 'stream/Props/bagdad_brigadeiro.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bagdad_beijinho.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_pacoca.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_pamonha.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bagdad_pastel.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_pizza.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bagdad_coxinha.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_coconut.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_maca.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bagdad_paodequeijo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_cupcake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Props/bag_sorvete.ytyp'